PictureGallery/Controllers/PictureController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.IO;
using System.Net;
using System.Web.Mvc;
using CloudinaryDotNet;
using CloudinaryDotNet.Actions;
using Microsoft.AspNet.Identity;
using MvcFileUploader.Models;
using PictureGallery.Models;

namespace PictureGallery.Controllers
{
    [Authorize]
    public class PictureController : BaseController
    {
        //add your own credentials
        readonly Cloudinary cloudinary = new Cloudinary(new Account(
                        ConfigurationManager.AppSettings["cloudinaryId"],
                        ConfigurationManager.AppSettings["cloudinaryKey"],
                        ConfigurationManager.AppSettings["cloudinarySecret"]));
        // GET: Gallery
        public ActionResult Index()
        {
            return View(GetAllPicturesOfCurrentUser());
        }

        public ActionResult UploadFile(int? entityId) // optionally receive values specified with Html helper
        {
            // here we can send in some extra info to be included with the delete url 
            var statuses = new List<ViewDataUploadFileResult>();
            for (var i = 0; i < Request.Files.Count; i++)
            {
                var x = new MvcFileSave();
                x.File = Request.Files[i];
                var filePath = Server.MapPath("~\\" + x.File.FileName);
                var fileStream = System.IO.File.Create(filePath);
                x.File.InputStream.Seek(0, SeekOrigin.Begin);
                x.File.InputStream.CopyTo(fileStream);
                fileStream.Close();
                //BinaryReader b = new BinaryReader(x.File.InputStream);
                //byte[] binImage = b.ReadBytes(Convert.ToInt32(x.File.InputStream.Length));
                //Stream stream = new MemoryStream(binImage);
                var uploadParams = new RawUploadParams
                {
                    File = new FileDescription(filePath)
                };
                var uploadResult = cloudinary.Upload(uploadParams);
                System.IO.File.Delete(filePath);
                x.UrlPrefix = uploadResult.SecureUri.AbsoluteUri;
                string currentUserId = User.Identity.GetUserId();
                Context.Pictures.Add(new Picture {Url = x.UrlPrefix, UserId = currentUserId});
                
                Context.SaveChanges();
                x.FileName = Request.Files[i].FileName; // default is filename suffixed with filetimestamp
                x.ThrowExceptions = false; //default is false, if false exception message is set in error property
                statuses.Add(new ViewDataUploadFileResult
                {
                    FullPath = x.UrlPrefix,
                    size = x.File.ContentLength,
                    deleteUrl = x.DeleteUrl,
                    thumbnailUrl = x.UrlPrefix,
                    url = x.UrlPrefix,
                    name = x.FileName
                });
            }

            //statuses contains all the uploaded files details (if error occurs then check error property is not null or empty)
            //todo: add additional code to generate thumbnail for videos, associate files with entities etc

            //adding thumbnail url for jquery file upload javascript plugin
            statuses.ForEach(x => x.thumbnailUrl = x.url);// + " width=300px height=200px"); // uses ImageResizer httpmodule to resize images from this url
            //setting custom download url instead of direct url to file which is default
            statuses.ForEach(x => x.url = Url.Action("DownloadFile", new { fileUrl = x.url, mimetype = x.type }));
            
            //server side error generation, generate some random error if entity id is 13
            if (entityId == 13)
            {
                var rnd = new Random();
                statuses.ForEach(x =>
                {
                    //setting the error property removes the deleteUrl, thumbnailUrl and url property values
                    x.error = rnd.Next(0, 2) > 0 ? "We do not have any entity with unlucky Id : '13'" : String.Format("Your file size is {0} bytes which is un-acceptable", x.size);
                    //delete file by using FullPath property
                    if (System.IO.File.Exists(x.FullPath)) System.IO.File.Delete(x.FullPath);
                });
            }

            var viewresult = Json(new { files = statuses });
            //for IE8 which does not accept application/json
            if (Request.Headers["Accept"] != null && !Request.Headers["Accept"].Contains("application/json"))
                viewresult.ContentType = "text/plain";

            return viewresult;
        }

        public JsonResult LoadBoobs()
        {
            var jsonString = new WebClient().DownloadString("http://api.oboobs.ru/noise/1");
            var index = jsonString.IndexOf("noise_preview/");
            var id = jsonString.Substring(index + 14, 5);
            var uploadParams = new RawUploadParams
            {
                File = new FileDescription("http://media.oboobs.ru/noise/"+ id + ".jpg")
            };

            var uploadResult = cloudinary.Upload(uploadParams);
            string currentUserId = User.Identity.GetUserId();
            Context.Pictures.Add(new Picture { Url = uploadResult.SecureUri.AbsoluteUri, UserId = currentUserId });

            Context.SaveChanges();
            return Json(uploadResult.SecureUri.AbsoluteUri);
        }

        public ActionResult DownloadFile(string fileUrl, string mimetype)
        {
            return Redirect(fileUrl);
        }

        public List<string> GetAllPicturesOfCurrentUser()
        {
            string currentUserId = User.Identity.GetUserId();

            //var result = Context.Pictures.Where(p => p.UserId.ToString() == currentUserId).Select(l => l.Url).ToList();
            var result = Context.Pictures.Where(p => p.UserId == currentUserId).Select(u => u.Url).ToList();
            return result;
        }
    }
}

PictureGallery/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
    <script type="text/javascript" src="/Scripts/mvcfileupload/vendor/bootstrap.min.js"></script>
    <!-- jQuery UI styles -->
    <link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/themes/smoothness/jquery-ui.css" id="theme">

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    @if (Request.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Pictures", "Index", "Picture")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p align="right">&copy; @DateTime.Now.Year - Egor Laptenok</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

PictureGallery/Views/Shared/_LoadBoobsView.cshtml
<html>
<head>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-2.1.3.js"></script>

</head>
    <body>
        <input type="button" value="Load boobs" id="load-boobs" class="btn btn-default" style="margin-bottom: 10px"/>
        <script>
            $(document).ready(function () {
                $('#load-boobs').click(function () {
                    $.ajax({
                        type: 'POST',
                        url: '/Picture/LoadBoobs',
                        dataType: 'json',
                        success: function (response) {
                            $('#links').append('<div id="pics" style="width: 100px;height: 100px;overflow: hidden;display: inline-block; float: left"><a href='
                                + response + ' data-gallery><img src=' + response + ' alt="picture" style="width: auto;height: 200px;margin: -30px 0 0 -30px;" /> </a></div>');
                        }
                    });
                });
            });
        </script>

    </body>
</html>

PictureGallery/Views/Shared/_MvcFileUpload.cshtml
@using System.Globalization
@using MvcFileUploader.Models
@model MvcFileUploader.Models.FileUploadViewModel
@{
    var formId = "fileupload" + Guid.NewGuid();    

    var maxNoOfFiles = Model.MaxNumberOfFiles.HasValue ? Model.MaxNumberOfFiles.Value.ToString(CultureInfo.InvariantCulture) : "undefined";
}
        
<!-- file upload dialog/inline form-->


    <form id="@formId" action="@Model.UploadUrl" method="POST" enctype="multipart/form-data">
        <div class="row fileupload-buttonbar">                    
            <div class="col-lg-7">
                
                <button type="submit" class="btn btn-primary start">
                    <i class="glyphicon glyphicon-upload"></i>
                    <span>Start upload</span>
                </button>
                <button type="reset" class="btn btn-warning cancel">
                    <i class="glyphicon glyphicon-ban-circle"></i>
                    <span>Cancel upload</span>
                </button>
            </div>

            <!-- The global file processing state -->
            <span class="fileupload-process"></span>
            <!-- The global progress state -->
            <div class="col-lg-5 fileupload-progress fade">
                <!-- The global progress bar -->
                <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                    <div class="progress-bar progress-bar-success" style="width: 0%;"></div>
                </div>
                <!-- The extended global progress state -->
                <div class="progress-extended">&nbsp;</div>
            </div>
        </div>
        <!-- The table listing the files available for upload/download -->
        <table role="presentation" class="table table-striped"><tbody class="files"></tbody></table>
        
        <!-- Additional values to be posted with form-->
        @foreach (var postItem in Model.PostValuesWithUpload)
        {
            @Html.Hidden(postItem.Key, postItem.Value)
        }
    </form>


<!--template and scripts-->
@if (Model.RenderSharedScript)
{
    <!-- The template to display files available for upload -->
        <script id="template-upload" type="text/x-tmpl">
        {% for (var i=0, file; file=o.files[i]; i++) { %}
            <tr class="template-upload fade">
                <td>
                    <span class="preview"></span>
                </td>
                <td>
                    <p class="name">{%=file.name%}</p>
                    <strong class="error text-danger"></strong>
                </td>
                <td>
                    <p class="size">Processing...</p>
                    <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="progress-bar progress-bar-success" style="width:0%;"></div></div>
                </td>
                <td>
                    {% if (!i && !o.options.autoUpload) { %}
                        <button class="btn btn-primary start" disabled>
                            <i class="glyphicon glyphicon-upload"></i>
                            <span>Start</span>
                        </button>
                    {% } %}
                    {% if (!i) { %}
                        <button class="btn btn-warning cancel">
                            <i class="glyphicon glyphicon-ban-circle"></i>
                            <span>Cancel</span>
                        </button>
                    {% } %}
                </td>
            </tr>
        {% } %}
        </script>
        <!-- The template to display files available for download -->
        <script id="template-download" type="text/x-tmpl">
        {% for (var i=0, file; file=o.files[i]; i++) { %}
            <tr class="template-download fade">
                <td>
                    <span class="preview">
                        {% if (file.thumbnailUrl) { %}
                            <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" data-gallery><img src="{%=file.thumbnailUrl%}" width="300" height="200"></a>
                        {% } %}
                    </span>
                </td>
                <td>
                    <p class="name">
                        {% if (file.url) { %}
                            <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" {%=file.thumbnailUrl?'data-gallery':''%}>{%=file.name%}</a>
                        {% } else { %}
                            <span>{%=file.name%}</span>
                        {% } %}
                    </p>
                    {% if (file.error) { %}
                        <div><span class="label label-danger">Error</span> {%=file.error%}</div>
                    {% } %}
                </td>
                <td>
                    <span class="size">{%=o.formatFileSize(file.size)%}</span>
                </td>                
            </tr>
        {% } %}
        </script>


    <!-- Blueimp Jquery File Upload-->
    
    <script type="text/javascript" src="/Scripts/mvcfileupload/blueimp/jquery.ui.widget.js"></script>
    <script type="text/javascript" src="/Scripts/mvcfileupload/blueimp/tmpl.min.js"></script>
    <!-- The Load Image plugin is included for the preview images and image resizing functionality -->
    <script src="/Scripts/mvcfileupload/blueimp/load-image.min.js"></script>
    <!-- The Canvas to Blob plugin is included for image resizing functionality -->
    <script src="/Scripts/mvcfileupload/blueimp/canvas-to-blob.min.js"></script>
    
    <script type="text/javascript" src="/Scripts/mvcfileupload/blueimp/jquery.iframe-transport.js"></script>
    <script type="text/javascript" src="/Scripts/mvcfileupload/blueimp/jquery.fileupload.js"></script>
    <script type="text/javascript" src="/Scripts/mvcfileupload/blueimp/jquery.fileupload-process.js"></script>
    <script type="text/javascript" src="/Scripts/mvcfileupload/blueimp/jquery.fileupload-image.js"></script>
    <script type="text/javascript" src="/Scripts/mvcfileupload/blueimp/jquery.fileupload-validate.js"></script>
    <script type="text/javascript" src="/Scripts/mvcfileupload/blueimp/jquery.fileupload-ui.js"></script>    
    
    <!-- Blueimp styles / see blueimp docs for styling requirements for jquery ui -->
    <link rel="stylesheet" href="/Content/mvcfileupload/blueimp/jquery.fileupload.css">
    <link rel="stylesheet" href="/Content/mvcfileupload/blueimp/jquery.fileupload-ui.css">
    
    if (Model.UIStyle == UploadUI.JQueryUI)
    {
       <script type="text/javascript" src="/Scripts/mvcfileupload/blueimp/jquery.fileupload-jquery-ui.js"></script>
    }
}
<!--template and scripts end-->

    <script type="text/javascript">
        jQuery(document).ready(function($) {
            // Initialize the jQuery File Upload widget:
            $('#@(formId)').fileupload({ url: '@Model.UploadUrl' });

            $('#@(formId)').fileupload('option', {
                dropZone: $('#@(formId)'),
                maxFileSize: @Model.MaxFileSizeInBytes,
                maxNumberOfFiles: @maxNoOfFiles,
                disableImagePreview: @(Model.DisableImagePreview ? "true" : "false"),
                resizeMaxWidth: 1920,
                resizeMaxHeight: 1200,
                acceptFileTypes: @Model.FileTypes,
            });
        });
    </script>

PictureGallery/Views/Shared/_MvcFileUploaderLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>bts</title>    
           
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>        
    
    <!-- Bootstrap styles -->
    <link rel="stylesheet" href="/Content/mvcfileupload/vendor/bootstrap.min.css">

    
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="navbar-brand" href="#">Project name</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="active"><a href="#">Home</a></li>
              <li><a href="#about">About</a></li>
              <li><a href="#contact">Contact</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <h3>Mvc File uploader Demo</h3>
        
        @RenderBody()

    </div> <!-- /container -->    
            
    <!-- For bootstrap modal dialog-->
    <script type="text/javascript" src="/Scripts/mvcfileupload/vendor/bootstrap.min.js"></script>

    @RenderSection("Scripts", false)
</body>
</html>

PictureGallery/Views/Shared/_MvcFileUploaderLayout_jui.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>jui</title>    
           
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
    <!-- jQuery UI styles -->
    <link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/themes/smoothness/jquery-ui.css" id="theme">

</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Project name</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="active"><a href="#">Home</a></li>
              <li><a href="#about">About</a></li>
              <li><a href="#contact">Contact</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <h3>Mvc File uploader Demo</h3>
        
        @RenderBody()

    </div> <!-- /container -->        

    @RenderSection("Scripts", false)
</body>
</html>